### ISSUE TITLE
Failed npm test

### ISSUE THREAD

**Issue by Philippe-M** [flyve-mdm/web-mdm-dashboard#349]
I've this error whem i'm start npm test

```
#npm test

> web-admin-dashboard@0.1.0 test /home/xxxxx/Téléchargements/flyve/web-mdm-dashboard
> node scripts/test.js --env=jsdom

fs.js:1376
    throw error;
    ^

Error: watch /home/xxxxx/Téléchargements/flyve/web-mdm-dashboard/node_modules/eslint/node_modules/esprima/bin ENOSPC
    at _errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1374:19)
    at Object.fs.watch (fs.js:1400:11)
    at NodeWatcher.watchdir (/home/xxxxx/Téléchargements/flyve/web-mdm-dashboard/node_modules/sane/src/node_watcher.js:175:20)
    at Walker.<anonymous> (/home/xxxxx/Téléchargements/flyve/web-mdm-dashboard/node_modules/sane/src/common.js:127:12)
    at emitTwo (events.js:126:13)
    at Walker.emit (events.js:214:7)
    at /home/xxxxx/Téléchargements/flyve/web-mdm-dashboard/node_modules/walker/lib/walker.js:69:16
    at go$readdir$cb (/home/xxxxx/Téléchargements/flyve/web-mdm-dashboard/node_modules/graceful-fs/graceful-fs.js:149:14)
    at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! Test failed.  See above for more details.

```

**Comment by Philippe-M** [comment]
@Gianfranco97 : i'm testing on my pc (Fedora 27), npm 5.6.0.

**Comment by Gianfranco97** [comment]
@Philippe-M try updating your code with develop and try again

```
$ git fetch origin develop 
$ git rebase origin/develop
$ npm install 
$ npm test
```

**Comment by Gianfranco97** [comment]
I don't understand what may be happening in your case, could you please provide us with the error report generated by npm?

**Comment by Philippe-M** [comment]
I do not have an error report or I do not know where to find it.

**Comment by CharlyJazz** [comment]
- Delete the npm cache folder in your home directory
- Run the commando of npm to clear the cache with force tag
- Update Node version to release version
- Use Yarn instead NPM to install and run script like the test

Tell me if your error persist

**Comment by ajsb85** [comment]
How to fix NodeJS/NPM ENOSPC error on Linux
http://opentechnics.com/how-to-fix-node-js-enospc-error-on-linux/

**Comment by Gianfranco97** [comment]
Since we have not received any new feedback for this issue, we closed it.

If you have any new information please let us know
