### ISSUE TITLE
UglifyJsPlugin has been removed

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/web-mdm-dashboard#412]
Error: webpack.optimize.UglifyJsPlugin has been removed, please use config.optimization.minimize instead.

```console
npm run-script build

> web-admin-dashboard@0.1.0 build C:\Users\<user>\flyve-mdm\web-mdm-dashboard
> node scripts/build.js

C:\Users\<user>\flyve-mdm\web-mdm-dashboard\node_modules\webpack\lib\webpack.js:162
                        throw new RemovedPluginError(errorMessage);
                        ^

Error: webpack.optimize.UglifyJsPlugin has been removed, please use config.optimization.minimize instead.
    at Object.get [as UglifyJsPlugin] (C:\Users\<user>\flyve-mdm\web-mdm-dashboard\node_modules\webpack\lib\webpack.js:162:10)
    at Object.<anonymous> (C:\Users\<user>\flyve-mdm\web-mdm-dashboard\config\webpack.config.prod.js:275:26)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\<user>\flyve-mdm\web-mdm-dashboard\scripts\build.js:21:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! web-admin-dashboard@0.1.0 build: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the web-admin-dashboard@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<user>\AppData\Roaming\npm-cache\_logs\2018-03-05T23_57_09_962Z-debug.log

C:\Users\alexa\flyve-mdm\web-mdm-dashboard>
```

**Comment by Gianfranco97** [comment]
This problem is generated when updating Webpack to version 4, at the moment we are waiting for the update of Create React App that would integrate the configuration to work with it.
